version: '3.9'
services: 
  db:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog-app
    ports: 
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  app: 
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    depends_on: 
      - db
    ports:
      - 3000:3000
    env_file: 
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/blog-app
      - NODE_ENV=production
