version: '3'
services: 
  postgres:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog-app
    ports: 
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  app: 
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/blog-app"

volumes:
  postgres-data: