version: '3'
services: 
  postgres_db:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog-app
    ports: 
      - 5433:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  app: 
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    environment:
      # App Settings
      - NODE_ENV = ${NODE_ENV}
      - PORT = ${PORT}
      - BASEURL = ${BASEURL}

      # TypeOrm
      - TYPEORM_URL = "postgresql://postgres:150901@localhost:5433/blog-app"

      # JWT 
      - JWT_SECRET = ${JWT_SECRET}
      - JWT_EXPIRATION = ${JWT_EXPIRATION}

      # NODEMAILER
      - MAIL_HOST = ${MAIL_HOST}
      - MAIL_PORT = ${MAIL_PORT}
      - MAIL_USER = ${MAIL_USER}
      - MAIL_PASS = ${MAIL_PASS}

      # CLOUDINARY
      - CLOUDINARY_CLOUD_NAME = ${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY = ${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET = ${CLOUDINARY_API_SECRET}

      # MULTER
      - MULTER_DEST = ${MULTER_DEST}
    volumes:
      - .:/app
    depends_on: 
      - postgres_db

volumes:
  postgres-data: